spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bkr_monitor
    username: bkr_user
    password: bkr_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ml-service:
  base-url: http://localhost:8001

logging:
  level:
    root: INFO
    ua.bkr.monitor: DEBUG
    org.hibernate.SQL: DEBUG